# Generated by Django 4.1.4 on 2022-12-11 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_destinations',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='دوستان'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_destination_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مقصد پیش فرض'),
        ),
    ]
