# Generated by Django 4.1.4 on 2023-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todos_creator_alter_todos_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[(0, 'انجام شده'), (1, 'در دست اقدام')], default='un', max_length=2, verbose_name='وضعیت'),
        ),
    ]
