# Generated by Django 4.1.4 on 2023-02-02 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_todos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('428fd196-1748-4b03-b328-18a4121de63c'), editable=False, unique=True),
        ),
    ]
