# Generated by Django 4.1.4 on 2023-02-05 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todos_status_alter_todos_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AddField(
            model_name='todos',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('1dd7074d-83c9-43c6-9c2c-a479c855bebf'), editable=False, unique=True),
        ),
    ]
