# Generated by Django 4.1.4 on 2023-02-05 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_todos_created_todos_modified_alter_todos_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'حداقل طول 3 کاراکتر باشد.')], verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='unique_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
